[server]
port = 8501
address = "localhost"
maxUploadSize = 200
maxMessageSize = 200

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[browser]
serverAddress = "localhost"
serverPort = 8501

[runner]
magicEnabled = true